services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - video-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=video_highlights
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env
    networks:
      - video-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  video-network:
    external: true

volumes:
  postgres_data:
    external: true 