version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=step1_video_highlight_extractor-db-1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=video_highlights_test
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env
    networks:
      - app-network
      - step1_video_highlight_extractor_default
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge
  step1_video_highlight_extractor_default:
    external: true

volumes:
  postgres_data:
    external: true 